apiVersion: api.g8s.io/v1alpha1
kind: Login
metadata:
  name: riley
spec:
  username: riley
  length: 12
  characterset: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
---
apiVersion: api.g8s.io/v1alpha1
kind: Login
metadata:
  name: root
spec:
  username: root
  length: 32
  characterset: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*()<>?{}[]-_=+\/|'
