# permissions for end users to edit logins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: login-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kb
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
  name: login-editor-role
rules:
- apiGroups:
  - api.g8s.io
  resources:
  - logins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.g8s.io
  resources:
  - logins/status
  verbs:
  - get
